### ISSUE TITLE
[Bug] Has anyone been able to get the @clack/prompts example working with Bun?

### ISSUE THREAD

**Issue by asibilia** [bombshell-dev/clack#170]
**Environment**

- OS: macOS
- Node Version: `v19.7.0`
- Package: `@clack/prompts`
- Package Version: `v0.2.0`

**Describe the bug**
When running the StackBlitz example from the documentation using Bun, the process exits after the first user input rather than completing all questions.

**To Reproduce**
https://github.com/asibilia/cli-tool

- Clone repo linked above ☝🏼 
- `bun install`
- Run script using `bun index.ts`

**Expected behavior**
Should run the example script from the docs as expected.

Issue over on the Bun repo here: https://github.com/oven-sh/bun/issues/6052

**Comment by akira-cn** [comment]
I found this way will temporary solve the problem.

Insert `await void(0)` between each command.

```js
await text({
    ...
});

await void(0);

await text({
    ...
});
```

**Comment by ChristoferMendes** [comment]
> I found this way will temporary solve the problem.
> 
> Insert `await void(0)` between each command.
> 
> ```js
> await text({
>     ...
> });
> 
> await void(0);
> 
> await text({
>     ...
> });
> ```

This does not worked out for me 😔

But I was curious, what exactly does await void(0) do and why would that be a solution?

**Comment by jhormanrus** [comment]
Looks like this issue has already been addressed in the latest release of Bun, v1.0.18. You can find more details about the fix in the release notes: [Bun v1.0.18 Release Notes](https://bun.sh/blog/bun-v1.0.18#fixed-hang-when-reading-from-process-stdin).

**Comment by FractalHQ** [comment]
Bun runs it fine, but chokes on the build:

```ts
❯ bun build index.ts
1 | s l,erase as d}from"sisteransi";import{stdin as $,stdout as k}from"node:process";import*as f from"node:readline";import
                                                          ^
error: No matching export in "node:process" for import "stdin"
    at /Users/bew/dev/scripts/tui/lss/node_modules/@clack/core/dist/index.mjs:1:55

1 | s d}from"sisteransi";import{stdin as $,stdout as k}from"node:process";import*as f from"node:readline";import _ from"node
                                                                     ^
error: No matching export in "node:process" for import "stdout"
    at /Users/bew/dev/scripts/tui/lss/node_modules/@clack/core/dist/index.mjs:1:66
```

**Comment by natemoo-re** [comment]
I'm going to close this since 1) it has been reported as fixed and 2) Bun considers broken packages as bugs in their Node compatibility layer, which is their responsibility to maintain.

There's an upstream issue for any further discussion. https://github.com/oven-sh/bun/issues/6052

As for running the build, it's best for all contributors to use the same toolchain. We currently use Node + `pnpm`.
